# config_cpu.yaml
workerPoolSpecs:
    machineSpec:
        machineType: n1-highmem-2 # This specifies a machine with 2 vCPUs and 13 GB of memory
    replicaCount: 1
    containerSpec:
        imageUri: europe-west1-docker.pkg.dev/mlops-exercises-484208/my-first-repository-2026/artifact-repo-image:latest
        env:
        - name: WANDB_API_KEY
          value: <your-wandb-api-key>